### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by danieldacruzferreira** [joaocosta/lib_mysqludf_ta#3]
Hello

I got an error on install:
#1127 - Can't find symbol 'ta_stddevp' in library

This is the query that I ran

use mysql;
drop function if exists ta_ema;
drop function if exists ta_max;
drop function if exists ta_min;
drop function if exists ta_previous;
drop function if exists ta_rsi;
drop function if exists ta_sma;
drop function if exists ta_stddevp;
drop function if exists ta_sum;
drop function if exists ta_tr;

CREATE FUNCTION ta_ema RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_max RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_min RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_previous RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_rsi RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_sma RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_stddevp RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_sum RETURNS REAL SONAME 'lib_mysqludf_ta.dll';
CREATE FUNCTION ta_tr RETURNS REAL SONAME 'lib_mysqludf_ta.dll';

I put this dll on mysql plugin folder: lib_mysqludf_ta-master\windows\Release\lib_mysqludf_ta.dll

**Comment by joaocosta** [comment]
Hi @danieldacruzferreira . 

Did you compile your own dll, or are you using the one at https://github.com/joaocosta/lib_mysqludf_ta/blob/master/windows/Release/lib_mysqludf_ta.dll ?

I suspect what happened is that the dll at https://github.com/joaocosta/lib_mysqludf_ta/blob/master/windows/Release/lib_mysqludf_ta.dll  was compiled before the ta_stddevp function was introduced, so it's not in that binary file.

Maybe you could try to compile it yourself using the Visual C project folder at https://github.com/joaocosta/lib_mysqludf_ta/tree/master/windows ?

I will try to compile it at some point, but time is short and I can't guarantee when I'll get around to it.

Thanks for the report !

**Comment by danieldacruzferreira** [comment]
Hi @joaocosta 

I'm using the one at  https://github.com/joaocosta/lib_mysqludf_ta/blob/master/windows/Release/lib_mysqludf_ta.dll

I checked the windows project and actually it does not have the function ta_stddevp

I will try to update the project and compile it.

thank you

**Comment by joaocosta** [comment]
It took a while, but I've updated the windows project with the the missing function and recompiled the binary DLL in 32 and 64 bit formats
